== Parte I: Fundamentos Básicos

*Lorem Ipsum* is simply dummy text of the printing and typesetting industry.
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type
specimen book. It has survived not only five centuries, but also the leap into
electronic typesetting, remaining essentially unchanged. It was popularised in
the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
and more recently with desktop publishing software like Aldus PageMaker
including versions of Lorem Ipsum.

include::../codes/example1.adoc[]

include::../tips/tip1.adoc[]

=== Interdisciplinaridade

Relação com outras áreas:

- Acústica e Arquitetura
- Música e composição
- Psicologia musicoterapia
- Engenharia Elétrica
- Telecomunicações
- Computação


=== História das tecnologias musicais

Ishkur Guide to Electronic Music


=== Definicão de som, audio e audio digital

=== Propriedades do som

* Propriedades do som e relações cognitivas
    - Duração
    - Altura
    - Dinâmica
    - Timbre
* Sistema temperado e Notas musicais
* Intervalos
* Percepção de altura (psicoacústica)


=== Visão do campo hoje: Congressos, revistas, cursos, etc.

.Lightweight Markup
****
Writing languages that let you type less and express more.
****

